"""empty message

Revision ID: f20426c7646b
Revises: 
Create Date: 2024-08-29 20:06:32.215848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20426c7646b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BRANCH', sa.Integer(), nullable=True),
    sa.Column('GM', sa.Integer(), nullable=True),
    sa.Column('_1G', sa.Integer(), nullable=True),
    sa.Column('_1K', sa.Integer(), nullable=True),
    sa.Column('_1R', sa.Integer(), nullable=True),
    sa.Column('_2AG', sa.Integer(), nullable=True),
    sa.Column('_2AK', sa.Integer(), nullable=True),
    sa.Column('_2AR', sa.Integer(), nullable=True),
    sa.Column('_2BG', sa.Integer(), nullable=True),
    sa.Column('_2BK', sa.Integer(), nullable=True),
    sa.Column('_2BR', sa.Integer(), nullable=True),
    sa.Column('_3AG', sa.Integer(), nullable=True),
    sa.Column('_3AK', sa.Integer(), nullable=True),
    sa.Column('_3AR', sa.Integer(), nullable=True),
    sa.Column('_3BG', sa.Integer(), nullable=True),
    sa.Column('_3BK', sa.Integer(), nullable=True),
    sa.Column('_3BR', sa.Integer(), nullable=True),
    sa.Column('GMK', sa.Integer(), nullable=True),
    sa.Column('GMR', sa.Integer(), nullable=True),
    sa.Column('SCG', sa.Integer(), nullable=True),
    sa.Column('SCK', sa.Integer(), nullable=True),
    sa.Column('SCR', sa.Integer(), nullable=True),
    sa.Column('STG', sa.Integer(), nullable=True),
    sa.Column('STK', sa.Integer(), nullable=True),
    sa.Column('STR', sa.Integer(), nullable=True),
    sa.Column('COLLEGES', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cutoff')
    # ### end Alembic commands ###
